# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

schedules:
- cron: 0 0 1 1 *
  displayName: yearly schedule
  branches:
    include:
    - main

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    set -e  # Exit immediately if any command fails
    npm install
    npm i typescript
    npm run cytest
  displayName: 'npm install, install typescript and run Cypress tests'